"""Product vocabulary for the Indian catalogue generator.

Faker on its own produces things like "Handcrafted Steel Chair" - grammatical,
and obviously synthetic to anyone who has shopped online. Realism comes from
the shape of the data rather than the random word generator: brands that
actually sell in India, model naming that follows each category's conventions,
the attributes a shopper filters on, and price bands taken from what these
goods really cost in rupees.

Every price band below is (min, max) in whole rupees.
"""

# Department names must match those seeded by migration V9.
CATALOGUE = {
    "Mobile Phones": {
        # Lines are bound to their brand. Drawing the two independently
        # produced "Apple Galaxy M" and "Bose SoundCore" - which anyone who
        # knows the market spots at a glance, and a catalogue that fails that
        # glance is not realistic however good the prices look.
        "brand_lines": {
            "Samsung": ["Galaxy M", "Galaxy A", "Galaxy F", "Galaxy S"],
            "Xiaomi": ["Redmi Note", "Redmi", "Redmi A"],
            "realme": ["Narzo", "realme C", "realme GT", "realme P"],
            "OnePlus": ["Nord CE", "Nord", "OnePlus"],
            "vivo": ["V", "Y", "T", "X"],
            "OPPO": ["Reno", "A", "F", "K"],
            "iQOO": ["Z", "Neo", "iQOO"],
            "Motorola": ["Edge", "G", "E"],
            "POCO": ["X", "M", "F", "C"],
            "Nothing": ["Phone", "CMF Phone"],
            "Apple": ["iPhone"],
            "Google": ["Pixel", "Pixel a"],
        },
        "variants": ["4G", "5G", "Pro", "Pro+", "Ultra", "Lite"],
        "attributes": ["6GB RAM 128GB", "8GB RAM 128GB", "8GB RAM 256GB",
                       "12GB RAM 256GB", "12GB RAM 512GB"],
        "colours": ["Midnight Black", "Glacier Blue", "Aurora Green",
                    "Titanium Grey", "Pearl White", "Sunset Orange"],
        # A feature phone and a flagship differ by two orders of magnitude, and
        # a flat band would put every phone in the same filter bucket.
        "price": (6999, 159900),
        "weight": (160, 240),
        "blurb": "{brand} {line} with a {display} display, {camera} camera and {battery} battery.",
        "extras": {
            "display": ["6.1-inch AMOLED", "6.5-inch Super AMOLED",
                        "6.67-inch LCD 120Hz", "6.7-inch OLED", "6.78-inch AMOLED 144Hz"],
            "camera": ["50MP dual", "64MP triple", "108MP triple", "200MP quad", "48MP OIS"],
            "battery": ["5000mAh", "6000mAh", "4500mAh with 67W fast charging",
                        "5000mAh with 120W fast charging"],
        },
    },
    "Electronics": {
        "brand_lines": {
            "Sony": ["WH Headphones", "Bravia Smart TV", "SRS Speaker", "Soundbar"],
            "boAt": ["Rockerz", "Airdopes", "Stone Speaker", "Wave Smartwatch"],
            "JBL": ["Flip", "Go", "Tune", "Charge", "Partybox"],
            "Noise": ["ColorFit", "Buds", "Air Buds", "Luna Ring"],
            "Philips": ["Trimmer", "Air Fryer", "Steam Iron", "Audio System"],
            "LG": ["Smart TV", "Soundbar", "Monitor", "Air Purifier"],
            "Samsung": ["Smart TV", "Soundbar", "Galaxy Buds", "Monitor"],
            "Mi": ["Smart TV", "Power Bank", "Smart Band", "Air Purifier"],
            "Zebronics": ["Speaker", "Keyboard", "Headphone", "Monitor"],
            "Portronics": ["Power Bank", "Speaker", "Charger", "Webcam"],
            "Bose": ["QuietComfort", "SoundLink"],
            "Marshall": ["Emberton", "Acton", "Major"],
        },
        "variants": ["", "Pro", "Max", "Plus", "2nd Gen"],
        "attributes": ["Bluetooth 5.3", "Active Noise Cancellation", "40H Playtime",
                       "Wireless", "Dolby Atmos"],
        "colours": ["Black", "Blue", "Grey", "White", "Beige"],
        # One band for the whole department priced earbuds like televisions -
        # "Samsung Galaxy Buds, Rs 2,35,900" is the sort of thing that makes a
        # catalogue obviously synthetic. Electronics spans three orders of
        # magnitude, so the band has to follow the product line.
        "line_prices": {
            "WH Headphones": (1499, 34990), "Bravia Smart TV": (32990, 249900),
            "SRS Speaker": (1999, 39990), "Soundbar": (4999, 79990),
            "Rockerz": (799, 3999), "Airdopes": (799, 4999),
            "Stone Speaker": (999, 7999), "Wave Smartwatch": (1199, 5999),
            "Flip": (7999, 13999), "Go": (1999, 3999), "Tune": (1499, 7999),
            "Charge": (9999, 17999), "Partybox": (14999, 89990),
            "ColorFit": (999, 7999), "Buds": (999, 4999), "Air Buds": (999, 3999),
            "Luna Ring": (14999, 29990), "Trimmer": (799, 4999),
            "Air Fryer": (3999, 19990), "Steam Iron": (899, 4999),
            "Audio System": (2999, 24990), "Smart TV": (11999, 199900),
            "Monitor": (5999, 59990), "Air Purifier": (7999, 39990),
            "Galaxy Buds": (2999, 24990), "Power Bank": (499, 4999),
            "Smart Band": (1299, 5999), "Speaker": (399, 7999),
            "Keyboard": (299, 5999), "Headphone": (399, 7999),
            "Charger": (299, 2999), "Webcam": (899, 5999),
            "QuietComfort": (14999, 39990), "SoundLink": (9999, 29990),
            "Emberton": (7999, 19990), "Acton": (14999, 34990),
            "Major": (6999, 14999),
        },
        "price": (499, 249900),
        "weight": (120, 12000),
        "blurb": "{brand} {line} featuring {feature}. {warranty}.",
        "extras": {
            "feature": ["deep bass and clear vocals", "active noise cancellation",
                        "up to 40 hours of playback", "IPX5 water resistance",
                        "low-latency gaming mode"],
            "warranty": ["1 year manufacturer warranty", "2 year warranty",
                         "6 month warranty on accessories"],
        },
    },
    "Computers": {
        "brand_lines": {
            "HP": ["Pavilion", "Victus", "OmniBook", "15s"],
            "Dell": ["Inspiron", "Vostro", "XPS", "G15"],
            "Lenovo": ["IdeaPad", "ThinkPad", "LOQ", "Yoga"],
            "ASUS": ["VivoBook", "ZenBook", "TUF Gaming", "ROG Strix"],
            "Acer": ["Aspire", "Nitro", "Swift", "Predator"],
            "Apple": ["MacBook Air", "MacBook Pro"],
            "MSI": ["Modern", "Thin", "Katana"],
            "Infinix": ["INBook", "GT Book"],
        },
        # Apple has not shipped an Intel chip in years, so the shared
        # attribute pool would describe a machine that does not exist.
        "brand_attributes": {
            "Apple": ["M2 8GB 256GB", "M2 16GB 512GB", "M3 8GB 512GB",
                      "M3 Pro 18GB 1TB"],
        },
        "variants": ["", "15", "14", "Gaming", "Thin and Light"],
        "attributes": ["i5 12th Gen 8GB 512GB SSD", "i7 13th Gen 16GB 1TB SSD",
                       "Ryzen 5 8GB 512GB SSD", "Ryzen 7 16GB 512GB SSD",
                       "M2 8GB 256GB", "i3 11th Gen 8GB 256GB SSD"],
        "colours": ["Silver", "Space Grey", "Shadow Black", "Platinum"],
        "price": (24990, 289900),
        "weight": (1200, 2800),
        "blurb": "{brand} {line} laptop with {attribute}, {display} and Windows 11.",
        "extras": {
            "display": ["14-inch FHD", "15.6-inch FHD IPS", "16-inch WQXGA",
                        "13.6-inch Liquid Retina"],
        },
    },
    "Clothing": {
        "brands": ["Allen Solly", "Levis", "Biba", "W for Woman", "FabIndia",
                   "Manyavar", "Peter England", "Van Heusen", "Libas", "Roadster",
                   "HRX", "Aurelia"],
        "lines": ["Anarkali Kurta", "Straight Kurta", "Banarasi Saree",
                  "Cotton Saree", "Slim Fit Shirt", "Formal Trousers",
                  "Printed Kurti", "Sharara Set", "Lehenga Choli", "Nehru Jacket",
                  "Chinos", "Regular Fit Jeans", "Anarkali Gown", "Palazzo Set"],
        "variants": ["", "Set of 2", "with Dupatta", "Pack of 3"],
        "attributes": ["S", "M", "L", "XL", "XXL", "Free Size"],
        "colours": ["Maroon", "Navy Blue", "Mustard Yellow", "Emerald Green",
                    "Rani Pink", "Off White", "Charcoal", "Peach"],
        "price": (349, 24999),
        "weight": (180, 1400),
        "blurb": "{colour} {line} in {fabric}. {care}.",
        "extras": {
            "fabric": ["pure cotton", "rayon blend", "georgette", "chiffon",
                       "silk blend", "linen", "crepe"],
            "care": ["Machine wash cold", "Dry clean only", "Hand wash recommended"],
        },
    },
    "Shoes": {
        "brands": ["Nike", "adidas", "Puma", "Bata", "Woodland", "Campus",
                   "Sparx", "Red Chief", "Skechers", "Liberty"],
        "lines": ["Running Shoes", "Sneakers", "Formal Derby", "Sports Sandals",
                  "Trekking Boots", "Loafers", "Flip Flops", "Walking Shoes"],
        "variants": ["", "Pro", "Lite"],
        "attributes": ["UK 6", "UK 7", "UK 8", "UK 9", "UK 10", "UK 11"],
        "colours": ["Black", "White", "Navy", "Tan", "Grey", "Olive"],
        "price": (399, 18995),
        "weight": (400, 1300),
        "blurb": "{brand} {line} with {sole} and {upper} upper.",
        "extras": {
            "sole": ["cushioned EVA sole", "anti-skid rubber sole", "memory foam insole"],
            "upper": ["mesh", "genuine leather", "synthetic", "knitted"],
        },
    },
    "Home & Kitchen": {
        "brands": ["Prestige", "Hawkins", "Milton", "Cello", "Borosil", "Pigeon",
                   "Butterfly", "Wonderchef", "Tupperware", "Bajaj"],
        "lines": ["Pressure Cooker", "Non-Stick Tawa", "Mixer Grinder",
                  "Casserole Set", "Water Bottle", "Induction Cooktop",
                  "Dinner Set", "Kadai", "Electric Kettle", "Lunch Box"],
        "variants": ["", "3L", "5L", "750ml", "Set of 6", "1.5L"],
        "attributes": ["Stainless Steel", "Hard Anodised", "Borosilicate Glass",
                       "Food Grade Plastic"],
        "colours": ["Steel", "Black", "Red", "Blue"],
        "price": (199, 24995),
        "weight": (200, 9000),
        "blurb": "{brand} {line} made from {material}. {safety}.",
        "extras": {
            "material": ["food-grade stainless steel", "hard anodised aluminium",
                         "toughened borosilicate glass", "BPA-free plastic"],
            "safety": ["Dishwasher safe", "Gas and induction compatible",
                       "ISI certified", "Microwave safe"],
        },
    },
    "Furniture": {
        "brands": ["Nilkamal", "Godrej Interio", "Sleepwell", "Duroflex",
                   "Wakefit", "Urban Ladder", "Pepperfry"],
        "lines": ["Office Chair", "Study Table", "Queen Mattress", "Shoe Rack",
                  "Bookshelf", "Folding Bed", "TV Unit", "Wardrobe"],
        "variants": ["", "2 Door", "3 Seater", "6 inch"],
        "attributes": ["Engineered Wood", "Solid Sheesham", "Metal Frame", "Plastic"],
        "colours": ["Walnut Brown", "Wenge", "White", "Black"],
        "price": (999, 89999),
        "weight": (3000, 60000),
        "blurb": "{brand} {line} in {finish}. {assembly}.",
        "extras": {
            "finish": ["walnut finish engineered wood", "solid sheesham wood",
                       "powder-coated steel", "matte laminate"],
            "assembly": ["Carpenter assembly included", "DIY assembly, tools provided",
                         "Delivered pre-assembled"],
        },
    },
    "Beauty & Personal Care": {
        "brands": ["Lakme", "Mamaearth", "Himalaya", "Nivea", "Dot and Key",
                   "Minimalist", "Plum", "The Derma Co", "Biotique", "WOW"],
        "lines": ["Face Wash", "Vitamin C Serum", "Sunscreen SPF 50",
                  "Body Lotion", "Hair Oil", "Lipstick", "Kajal", "Face Cream",
                  "Shampoo", "Ubtan Face Mask"],
        "variants": ["", "100ml", "200ml", "30ml", "Pack of 2"],
        "attributes": ["For Oily Skin", "For Dry Skin", "All Skin Types",
                       "Paraben Free", "Dermatologically Tested"],
        "colours": ["", "Ruby Red", "Nude", "Coral"],
        "price": (99, 4999),
        "weight": (30, 500),
        "blurb": "{brand} {line} enriched with {ingredient}. {claim}.",
        "extras": {
            "ingredient": ["niacinamide", "hyaluronic acid", "aloe vera",
                           "turmeric and saffron", "argan oil", "salicylic acid"],
            "claim": ["Suitable for daily use", "Free from parabens and sulphates",
                      "Dermatologically tested", "Cruelty free and vegan"],
        },
    },
    "Sports & Outdoors": {
        "brands": ["Decathlon", "Nivia", "Cosco", "SG", "Yonex", "Kookaburra",
                   "HRX", "Strauss"],
        "lines": ["Cricket Bat", "Badminton Racket", "Football", "Yoga Mat",
                  "Dumbbell Set", "Skipping Rope", "Gym Gloves", "Cycling Helmet"],
        "variants": ["", "Size 5", "10kg", "6mm"],
        "attributes": ["Beginner", "Intermediate", "Professional"],
        "colours": ["Black", "Blue", "Red", "Green"],
        "price": (199, 34999),
        "weight": (150, 15000),
        "blurb": "{brand} {line} for {level} players. {detail}.",
        "extras": {
            "level": ["beginner", "intermediate", "professional"],
            "detail": ["Lightweight and durable", "Includes carry case",
                       "Anti-slip grip", "Weather resistant"],
        },
    },
    "Toys & Games": {
        "brands": ["Funskool", "Hasbro", "LEGO", "Mattel", "Skillmatics",
                   "Ravensburger", "Chicco"],
        "lines": ["Building Blocks", "Board Game", "Jigsaw Puzzle",
                  "Remote Control Car", "Soft Toy", "Learning Tablet",
                  "Play Kitchen", "Card Game"],
        "variants": ["", "Age 3+", "Age 6+", "1000 Pieces"],
        "attributes": ["Educational", "Multiplayer", "Battery Operated"],
        "colours": ["Multicolour", "Blue", "Pink"],
        "price": (149, 12999),
        "weight": (100, 4000),
        "blurb": "{brand} {line} - {benefit}. Suitable for {age}.",
        "extras": {
            "benefit": ["builds problem-solving skills", "encourages creative play",
                        "improves hand-eye coordination", "great for family game night"],
            "age": ["ages 3 and up", "ages 6 and up", "ages 8 and up", "all ages"],
        },
    },
    "Books": {
        "brands": ["Penguin", "HarperCollins", "Rupa", "Westland", "Bloomsbury",
                   "Scholastic", "Oxford"],
        "lines": ["Paperback Edition", "Hardcover Edition", "Illustrated Edition"],
        "variants": [""],
        "attributes": ["Fiction", "Non-Fiction", "Self Help",
                       "Competitive Exams", "Children's"],
        "colours": [""],
        "price": (99, 2499),
        "weight": (150, 900),
        "blurb": "{genre}. {pages} pages, published by {brand}.",
        "extras": {
            "genre": ["A gripping literary novel",
                      "A practical guide to personal finance",
                      "An illustrated story for young readers",
                      "A complete exam preparation guide",
                      "A landmark work of Indian history"],
            "pages": ["224", "312", "448", "180", "560"],
        },
    },
    "Automotive": {
        "brands": ["Bosch", "Castrol", "3M", "Amaron", "Exide", "MRF", "Steelbird"],
        "lines": ["Engine Oil", "Car Battery", "Wiper Blades", "Car Cover",
                  "Tyre Inflator", "Dashboard Polish", "Riding Helmet"],
        "variants": ["", "1L", "3.5L", "Set of 2"],
        "attributes": ["Petrol", "Diesel", "Universal Fit"],
        "colours": ["Black", "Silver"],
        "price": (249, 18999),
        "weight": (200, 20000),
        "blurb": "{brand} {line} - {detail}. {compat}.",
        "extras": {
            "detail": ["long-lasting protection", "OEM quality replacement",
                       "all-weather performance"],
            "compat": ["Fits most Indian hatchbacks and sedans",
                       "Check compatibility before ordering", "Universal fitment"],
        },
    },
    "Office Products": {
        "brands": ["Classmate", "Camlin", "Faber-Castell", "Luxor", "Cello",
                   "Navneet", "3M"],
        "lines": ["Notebook", "Gel Pen Set", "Sticky Notes", "File Folder",
                  "Whiteboard Marker", "Stapler", "Desk Organiser"],
        "variants": ["", "Pack of 10", "Pack of 5", "A4"],
        "attributes": ["Ruled", "Unruled", "Spiral Bound"],
        "colours": ["Blue", "Black", "Assorted"],
        "price": (39, 4999),
        "weight": (50, 2000),
        "blurb": "{brand} {line}. {detail}.",
        "extras": {
            "detail": ["Smooth writing experience",
                       "Ideal for office and school use",
                       "Made from recycled paper", "Long lasting ink"],
        },
    },
    "Pet Supplies": {
        "brands": ["Pedigree", "Whiskas", "Drools", "Himalaya", "Trixie", "Farmina"],
        "lines": ["Adult Dry Food", "Puppy Food", "Cat Food", "Chew Toy",
                  "Pet Shampoo", "Collar", "Feeding Bowl"],
        "variants": ["", "1.2kg", "3kg", "Medium", "Large"],
        "attributes": ["Chicken", "Lamb and Rice", "Ocean Fish", "Grain Free"],
        "colours": ["", "Red", "Blue"],
        "price": (99, 6499),
        "weight": (100, 15000),
        "blurb": "{brand} {line} - {detail}. {note}.",
        "extras": {
            "detail": ["complete and balanced nutrition",
                       "supports healthy coat and skin", "vet recommended"],
            "note": ["For adult dogs", "For kittens and cats",
                     "Suitable for all breeds"],
        },
    },
    "Health & Household": {
        "brands": ["Dettol", "Lizol", "Harpic", "Surf Excel", "Vim", "Colin",
                   "Godrej", "Savlon"],
        "lines": ["Disinfectant Liquid", "Floor Cleaner", "Toilet Cleaner",
                  "Detergent Powder", "Dishwash Gel", "Hand Sanitiser",
                  "Glass Cleaner"],
        "variants": ["", "1L", "500ml", "2kg", "Pack of 3"],
        "attributes": ["Citrus", "Lavender", "Original", "Lemon"],
        "colours": [""],
        "price": (49, 2999),
        "weight": (200, 5000),
        "blurb": "{brand} {line} - {claim}. {usage}.",
        "extras": {
            "claim": ["kills 99.9% of germs", "tough on stains, gentle on hands",
                      "long-lasting fragrance"],
            "usage": ["Dilute before use", "Safe on all surfaces",
                      "For daily cleaning"],
        },
    },
    "Baby": {
        "brands": ["Pampers", "Huggies", "Johnsons", "Chicco", "MamyPoko",
                   "Mee Mee", "LuvLap"],
        "lines": ["Diaper Pants", "Baby Wipes", "Baby Lotion", "Feeding Bottle",
                  "Baby Carrier", "Sterilizer", "Baby Powder"],
        "variants": ["", "Small", "Medium", "Large", "Pack of 72"],
        "attributes": ["0-6 Months", "6-12 Months", "1-2 Years"],
        "colours": ["", "Pink", "Blue"],
        "price": (99, 8999),
        "weight": (100, 3000),
        "blurb": "{brand} {line} - {claim}. {note}.",
        "extras": {
            "claim": ["gentle on delicate skin", "up to 12 hours of dryness",
                      "clinically tested for babies"],
            "note": ["Dermatologist tested", "Free from parabens",
                     "BPA free materials"],
        },
    },
    "Luggage": {
        "brands": ["American Tourister", "Skybags", "VIP", "Safari", "Wildcraft",
                   "Aristocrat"],
        "lines": ["Cabin Trolley", "Check-in Trolley", "Laptop Backpack",
                  "Duffel Bag", "Travel Organiser"],
        "variants": ["", "55cm", "68cm", "35L"],
        "attributes": ["Hard Shell", "Soft Shell", "Water Resistant"],
        "colours": ["Black", "Navy", "Teal", "Maroon"],
        "price": (599, 21999),
        "weight": (500, 6000),
        "blurb": "{brand} {line} with {feature}. {warranty}.",
        "extras": {
            "feature": ["360-degree spinner wheels", "TSA-approved combination lock",
                        "padded laptop compartment", "expandable main compartment"],
            "warranty": ["3 year international warranty", "5 year warranty",
                         "1 year warranty against manufacturing defects"],
        },
    },
    "Musical Instruments": {
        "brands": ["Yamaha", "Casio", "Kadence", "Juarez", "Fender", "Hertz"],
        "lines": ["Acoustic Guitar", "Digital Piano", "Tabla Set", "Harmonium",
                  "Ukulele", "Cajon", "Electric Guitar"],
        "variants": ["", "61 Keys", "38 inch", "Beginner Kit"],
        "attributes": ["Beginner", "Intermediate", "Professional"],
        "colours": ["Natural", "Black", "Sunburst"],
        "price": (1499, 89999),
        "weight": (1000, 25000),
        "blurb": "{brand} {line} - {detail}. {includes}.",
        "extras": {
            "detail": ["warm balanced tone", "responsive touch",
                       "handcrafted by Indian artisans"],
            "includes": ["Includes gig bag and picks", "Includes stand and adapter",
                         "Includes tuning tools"],
        },
    },
    "Tools & Home Improvement": {
        "brands": ["Bosch", "Stanley", "Black and Decker", "Taparia", "Cheston",
                   "Ibell"],
        "lines": ["Cordless Drill", "Screwdriver Set", "Angle Grinder",
                  "Measuring Tape", "Tool Kit", "Hammer", "Wrench Set"],
        "variants": ["", "12V", "18V", "Set of 25", "5m"],
        "attributes": ["Home Use", "Professional", "Heavy Duty"],
        "colours": ["Blue", "Yellow", "Red"],
        "price": (199, 24999),
        "weight": (200, 12000),
        "blurb": "{brand} {line} - {detail}. {safety}.",
        "extras": {
            "detail": ["ergonomic anti-slip grip", "hardened chrome vanadium steel",
                       "variable speed control"],
            "safety": ["ISI certified", "Includes safety guard",
                       "2 year warranty"],
        },
    },
    "Garden & Outdoor": {
        "brands": ["Ugaoo", "TrustBasket", "Sharpex", "Kraft Seeds", "Gardening Mart"],
        "lines": ["Seed Kit", "Ceramic Planter", "Garden Hose", "Pruning Shears",
                  "Organic Fertiliser", "Grow Bag", "Watering Can"],
        "variants": ["", "Pack of 5", "10m", "1kg"],
        "attributes": ["Indoor", "Outdoor", "Balcony"],
        "colours": ["Terracotta", "White", "Green"],
        "price": (99, 7999),
        "weight": (100, 10000),
        "blurb": "{brand} {line} - {detail}. {note}.",
        "extras": {
            "detail": ["ideal for balcony gardens", "UV stabilised and weatherproof",
                       "improves soil health naturally"],
            "note": ["Suitable for Indian climate", "Organic and chemical free",
                     "Easy to maintain"],
        },
    },
    "Movies & TV": {
        "brands": ["Sony Pictures", "Yash Raj Films", "Dharma", "Excel Entertainment",
                   "Universal", "Reliance Entertainment", "Eros", "Shemaroo"],
        "lines": ["Blu-ray", "DVD Collection", "Limited Edition Box Set",
                  "4K Ultra HD", "Collectors Edition", "Complete Season Set"],
        "variants": ["", "2 Disc", "3 Disc", "Steelbook"],
        "attributes": ["Hindi", "English", "Tamil", "Telugu", "Malayalam",
                       "Kannada", "Bengali", "Marathi"],
        "colours": [""],
        "price": (199, 3999),
        "weight": (100, 600),
        "blurb": "{genre} on {line}. {extras_note}.",
        "extras": {
            "genre": ["An award-winning drama", "A blockbuster action thriller",
                      "A beloved family comedy", "A critically acclaimed biopic"],
            "extras_note": ["Includes behind-the-scenes featurette",
                            "Remastered picture and sound",
                            "With subtitles in six languages"],
        },
    },
    "Video Games": {
        "brands": ["Sony", "Microsoft", "Nintendo", "Ubisoft", "EA Sports", "Rockstar"],
        "lines": ["PS5 Game", "Xbox Series X Game", "Nintendo Switch Game",
                  "Wireless Controller", "Gaming Headset"],
        "variants": ["", "Standard Edition", "Deluxe Edition"],
        "attributes": ["Action", "Sports", "Racing", "Adventure", "Strategy"],
        "colours": ["", "Black", "White"],
        "price": (499, 64999),
        "weight": (100, 1500),
        "blurb": "{line} - {detail}. {note}.",
        "extras": {
            "detail": ["an open-world adventure", "the latest season roster",
                       "competitive online multiplayer"],
            "note": ["Requires internet for online play", "Single and multiplayer",
                     "Region free"],
        },
    },
}


# Model or series names, shared across departments.
#
# Real products carry these - "Prestige Omega Deluxe", "Milton Thermosteel",
# "Bosch Endura" - and they are what makes a catalogue of fifty thousand items
# possible without repeating names. Without this dimension the vocabulary of a
# small department exhausts after a few hundred combinations: Movies & TV ran
# out at 75.
SERIES = [
    "", "Classic", "Pro", "Elite", "Prime", "Signature", "Essential", "Select",
    "Ultra", "Neo", "Max", "Active", "Smart", "Comfort", "Endura", "Vantage",
    "Aura", "Crest", "Zenith", "Nova", "Orbit", "Fusion", "Vertex",
]
